### ISSUE TITLE
czechgerman.py data source is dead

### ISSUE THREAD

**Issue by pjanx** [nijel/stardicter#3]
> Ten německý slovník je asi mrtvý
> Já jsem na něj koukal, když jsem zakládal projekt, ale tam byla hrstka slovíček, že to nemělo vůbec smysl přebírat.
> Když jsem se učil estonsky, tak jsem si zvládl sepsat víc slovíček, než bylo v tom německém :-)

In any case, I've written an e-mail to some address I've found on the site. It might be better to just remove it, though.

**Comment by nijel** [comment]
There are more dead sources in this repository. And I currently don't have any plans for maintenance here.
